every 1 second:
	loop all players:
		wipe loop-player's sidebar
		set name of sidebar of loop-player to "&e♡ &f중원 &e♡"
		set score "    &f    " in sidebar of loop-player to 5
		set score "   &f&l닉네임 &7%{닉네임::%loop-player%}%" in sidebar of loop-player to 4
		set score "         &f " in sidebar of loop-player to 3
		set score "   &f&l소지금 &a%{money::%loop-player%}%&f원" in sidebar of loop-player to 2
		set score "&f         " in sidebar of loop-player to 1